version: '3.3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    expose:
      - "5432"
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "/mnt/postgres/data:/var/lib/postgressql/data"